version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/taskmanagement
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: 